name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
    paths: 
      - "Back-End-Individual/TaskService/**"
      - ".github/workflows/ci-cd.yaml/"

  pull_request:
    branches:
      - main
  
env:
  PROJECT_PATH: 'TaskService/back-end.csproj'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
          
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to DockerHub
        uses: docker/login-action@v11
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: 'Back-End-Individual/TaskService' 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/Back-End-Individual:latest
